matrix:
  include:
    - language: python
      python: 3.6
      env:
        - DJANGO_SETTINGS_MODULE='BookHub.settings.test'
      install:
        - pip install -r BookHub/requirements/test.txt
      script:
        - flake8 BookHub
        - python BookHub/manage.py test BookHub

    - language: node_js
      node_js: 8.9.3
      before_install:
        - cd BookHub-frontend
      install:
        - npm install
      script:
        - npm run lint

cache:
  directories:
  - $HOME/.cache/pip
  - BookHub-frontend/node_modules     
