version: '3'


services:
  reverseproxy:
    image: nginx
    restart: always
    volumes:
      - ./docker/docker_provision/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/docker_provision/bookhub.com.template:/etc/nginx/conf.d/bookhub.com.template
      - app-statics:/static
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=bookhub.com
      - NGINX_PORT=80
      - BACKEND_UPSTREAM=bookhub-backend
    command: /bin/bash -c "envsubst '$${NGINX_PORT},$${NGINX_HOST},$${BACKEND_UPSTREAM}' < /etc/nginx/conf.d/bookhub.com.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
        - bookhub-backend

  bookhub-backend:
    image: bookhub-backend:prod
    build:
      context: ./BookHub
      dockerfile: $PWD/docker/bookhub-backend/Dockerfile
    command: gunicorn --workers 2 --bind 0.0.0.0:8000 BookHub.wsgi:application --access-logfile - --error-logfile -
    volumes:
        - ./BookHub:/srv/app
        - app-statics:/static
    environment:
      - DJANGO_SETTINGS_MODULE=BookHub.settings.prod
    expose:
      - "8000"

volumes:
  app-statics:

