# Generated by Django 2.0.3 on 2018-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0001_initial'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhubuser',
            name='favourites',
            field=models.ManyToManyField(through='favourites.Favourite', to='books.Book'),
        ),
        migrations.AddField(
            model_name='bookhubuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='bookhubuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
