# Generated by Django 2.0.3 on 2018-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
        ('books', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhubuser',
            name='favourites',
            field=models.ManyToManyField(through='favourites.Favourite', to='books.Book'),
        ),
    ]
