# Generated by Django 2.0.3 on 2018-03-25 15:42

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhubuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and ./_ only.', max_length=30, unique=True, validators=[accounts.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
