# Generated by Django 2.0.3 on 2018-03-25 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180325_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhubuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
